baseurl = "https://fbegyn.gitlab.io/personalsite"
title = "francisbegyn"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Francis Begyn"
    description = "My little place on the internet"
    keywords = "blog,developer,personal,linux,go,rust"
    info = "Student, light tech and I dabble in monitoring"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/fbegyn/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/fbegyn/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/fbegyn/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
