baseurl = "https://francis.begyn.be"
title = "Francis Begyn"
theme = "development"
#languagecode = "en"
#defaultcontentlanguage = "en"

paginate = 20

[params]
    author = "Francis Begyn"
    info = "System engineering and SRE enthousiast"
    keywords = "blog,developer,personal"
    description = "Development"
    avatarurl = "images/profile.jpg"


# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/fbegyn/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/fbegyn/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/fbegyn/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
