baseurl = "https://francis.begyn.be" # Hostname (and path) to the root.
title = "Francis Begyn" # Site title.
theme = "development" # Set the theme.
#languagecode = "en" # The site’s language code used to generate RSS.
#defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

[params] # theme parameters
    author = "Francis Begyn" # Author's name.
    info = "System engineering and SRE enthousiast" # Author's job title or info.
    keywords = "blog,developer,personal" # Site keywords.
    description = "Development"
    avatarurl = "images/profile.jpg" # Contain the path of the optionnal avatar in the static folder.


# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/fbegyn/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/fbegyn/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/fbegyn/"
